name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: Clone Plugins
        uses: actions/checkout@v2

      - name: Build Plugin
        run: dotnet publish -c Release src

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Artemis.Plugins.Mqtt
          path: src/Artemis.Plugins.Mqtt/bin/x64/Release/net8.0/publish
